const Mobiledata = [
    {
      id: 1,
      name: 'iPhone SE (2022)',
      brandName: 'Apple',
      type: 'Smartphone',
      processor: 'A15 Bionic chip',
      memory: '64GB',
      color: 'Blue',
      OS: 'iOS 15',
      price: 429.99,
      description: 'A compact yet powerful iPhone with the latest A15 chip and advanced camera features.'
    },
    {
      id: 2,
      name: 'Samsung Galaxy A52',
      brandName: 'Samsung',
      type: 'Smartphone',
      processor: 'Snapdragon',
      memory: '128GB',
      color: 'Black',
      OS: 'Android 11',
      price: 349.99,
      description: 'Mid-range Samsung phone with a versatile camera setup and AMOLED display.'
    },
    {
      id: 3,
      name: 'Google Pixel 5a',
      brandName: 'Google',
      type: 'Smartphone',
      processor: 'Snapdragon',
      memory: '128GB',
      color: 'Black',
      OS: 'Android 12',
      price: 449.99,
      description: 'Google\'s budget-friendly phone with a great camera, 5G capability, and long battery life.'
    },
    {
      id: 4,
      name: 'OnePlus Nord N200',
      brandName: 'OnePlus',
      type: 'Smartphone',
      processor: 'Snapdragon',
      memory: '64GB',
      color: 'Blue',
      OS: 'OxygenOS 11',
      price: 239.99,
      description: 'Affordable OnePlus phone with a 90Hz display, 5G connectivity, and a decent camera setup.'
    },
    {
      id: 5,
      name: 'Xiaomi Redmi Note 10',
      brandName: 'Xiaomi',
      type: 'Smartphone',
      processor: 'Snapdragon',
      memory: '128GB',
      color: 'White',
      OS: 'MIUI 12',
      price: 249.99,
      description: 'Value-for-money Xiaomi phone with a high-resolution display and good battery life.'
    },
    {
      id: 6,
      name: 'Realme 8 Pro',
      brandName: 'Realme',
      type: 'Smartphone',
      processor: 'Snapdragon',
      memory: '128GB',
      color: 'Blue',
      OS: 'Realme UI 2.0',
      price: 279.99,
      description: 'Realme phone with a 108MP camera, Super AMOLED display, and fast charging support.'
    },
    {
      id: 7,
      name: 'Motorola Moto G Power (2022)',
      brandName: 'Motorola',
      type: 'Smartphone',
      processor: 'Snapdragon',
      memory: '64GB',
      color: 'Gray',
      OS: 'Android 11',
      price: 199.99,
      description: 'Motorola phone known for its long battery life, solid performance, and near-stock Android experience.'
    },
    {
      id: 8,
      name: 'Sony Xperia 10 III',
      brandName: 'Sony',
      type: 'Smartphone',
      processor: 'Snapdragon',
      memory: '128GB',
      color: 'Black',
      OS: 'Android 11',
      price: 399.99,
      description: 'Sony phone with a triple-lens camera system, OLED display, and water-resistant design.'
    },
    {
      id: 9,
      name: 'Nokia G50',
      brandName: 'Nokia',
      type: 'Smartphone',
      processor: 'Snapdragon',
      memory: '128GB',
      color: 'Midnight Sun',
      OS: 'Android 11',
      price: 299.99,
      description: 'Nokia phone with 5G connectivity, a large display, and a durable build.'
    },
    {
      id: 10,
      name: 'Asus Zenfone 8',
      brandName: 'Asus',
      type: 'Smartphone',
      processor: 'Snapdragon',
      memory: '256GB',
      color: 'White',
      OS: 'Android 11',
      price: 699.99,
      description: 'Compact Asus phone with top-tier Snapdragon processor and a high-refresh-rate AMOLED display.'
    },
    {
        id: 11,
        name: 'iPhone 13',
        brandName: 'Apple',
        type: 'Smartphone',
        processor: 'A15 Bionic chip',
        memory: '128GB',
        color: 'Blue',
        OS: 'iOS 15',
        price: 799.99,
        description: 'The latest iPhone with an advanced chip and improved camera features.'
      },
      {
        id: 12,
        name: 'Galaxy S21 Ultra',
        brandName: 'Samsung',
        type: 'Smartphone',
        processor: 'Snapdragon',
        memory: '256GB',
        color: 'Phantom Black',
        OS: 'Android 11',
        price: 999.99,
        description: 'Flagship Samsung phone with a powerful Snapdragon processor.'
      },
      {
        id: 13,
        name: 'OnePlus 9 Pro',
        brandName: 'OnePlus',
        type: 'Smartphone',
        processor: 'Snapdragon',
        memory: '256GB',
        color: 'Morning Mist',
        OS: 'OxygenOS 11',
        price: 899.99,
        description: 'High-performance OnePlus flagship phone with a 120Hz display.'
      },
      {
        id: 14,
        name: 'Google Pixel 6 Pro',
        brandName: 'Google',
        type: 'Smartphone',
        processor: 'Tensor',
        memory: '128GB',
        color: 'Stormy Black',
        OS: 'Android 12',
        price: 899.99,
        description: 'Google\'s flagship phone with an advanced Tensor chip and improved camera capabilities.'
      },
      {
        id: 15,
        name: 'Xiaomi Mi 11 Ultra',
        brandName: 'Xiaomi',
        type: 'Smartphone',
        processor: 'Snapdragon',
        memory: '256GB',
        color: 'White',
        OS: 'MIUI 12',
        price: 1099.99,
        description: 'Powerful Xiaomi phone with a high-resolution camera and Snapdragon processor.'
      },
      {
        id: 16,
        name: 'Sony Xperia 1 III',
        brandName: 'Sony',
        type: 'Smartphone',
        processor: 'Snapdragon',
        memory: '256GB',
        color: 'Black',
        OS: 'Android 11',
        price: 1299.99,
        description: 'Sony\'s flagship phone with a 4K OLED display and advanced camera technology.'
      },
      {
        id: 17,
        name: 'Motorola Edge 20 Pro',
        brandName: 'Motorola',
        type: 'Smartphone',
        processor: 'Snapdragon',
        memory: '256GB',
        color: 'Blue',
        OS: 'Android 11',
        price: 699.99,
        description: 'Motorola\'s high-performance smartphone with a sleek design and AMOLED display.'
      },
  ];
  
  export default Mobiledata;
  